import type { Opportunity } from "./types";

export const demoOpportunities: Opportunity[] = [
  {
    id: "demo-byte-ai-pm",
    company: "字节跳动",
    role: "AI 产品经理",
    location: "北京 · 混合办公",
    stage: "preparing_application",
    stageLabel: "准备投递",
    priority: "high",
    sourceLabel: "示例 JD 快照",
    capturedAtLabel: "今天 09:42",
    nextEventLabel: "建议今天完成简历 V1",
    recommendation: "prepare_then_apply",
    recommendationLabel: "补充后投递",
    recommendationReason: "产品落地和跨团队协作证据充分，但商业化结果仍缺一个可核实指标。",
    evidenceCoverage: { strong: 4, weak: 2, missing: 1, unverified: 1 },
    requirements: [
      {
        id: "req-1",
        requirement: "负责 AI 产品从需求验证到上线迭代的完整闭环",
        importance: "critical",
        strength: "strong",
        evidence: "主导智能客服工作台从 0 到 1，上线后持续负责三轮策略迭代。",
        source: "基础简历 · 智能客服项目",
        verified: true,
      },
      {
        id: "req-2",
        requirement: "能够与算法、工程、运营团队共同定义效果指标",
        importance: "critical",
        strength: "strong",
        evidence: "建立意图识别准确率、转人工率与解决率的联合评估体系。",
        source: "项目复盘 · 2025 Q3",
        verified: true,
      },
      {
        id: "req-3",
        requirement: "理解大模型能力边界并能设计评测方案",
        importance: "important",
        strength: "weak",
        evidence: "有提示词测试和人工抽检经验，但尚未形成系统评测集。",
        source: "基础简历 · 能力描述",
        verified: true,
      },
      {
        id: "req-4",
        requirement: "有商业化产品或收入增长经验",
        importance: "important",
        strength: "unverified",
        evidence: "曾参与付费版本设计，但收入贡献和个人职责边界尚未确认。",
        source: null,
        verified: false,
      },
      {
        id: "req-5",
        requirement: "3 年以上互联网产品经验",
        importance: "critical",
        strength: "strong",
        evidence: "两段产品经历累计 4 年 2 个月。",
        source: "基础简历 · 工作经历",
        verified: true,
      },
    ],
    actions: [
      {
        id: "action-1",
        title: "确认商业化项目的结果指标",
        reason: "这决定该岗位是“优先投递”还是“补充后投递”。",
        dueLabel: "今天",
        priority: "urgent",
        status: "todo",
      },
      {
        id: "action-2",
        title: "审阅岗位简历 V1 的 3 处修改",
        reason: "初稿中有一处涉及职责边界，需要你确认。",
        dueLabel: "今天",
        priority: "high",
        status: "todo",
      },
      {
        id: "action-3",
        title: "练习“如何评估大模型效果”追问",
        reason: "当前证据偏弱，这会是面试官最容易深入追问的部分。",
        dueLabel: "投递前",
        priority: "normal",
        status: "todo",
      },
    ],
    activities: [
      {
        id: "activity-1",
        actor: "analysis",
        title: "完成岗位要求拆解",
        detail: "识别出 5 条关键要求，并关联到 4 条已确认经历。",
        timeLabel: "12 分钟前",
      },
      {
        id: "activity-2",
        actor: "system",
        title: "发现一个需要确认的事实",
        detail: "商业化项目的收入结果没有可追溯来源，已加入今日行动。",
        timeLabel: "10 分钟前",
      },
      {
        id: "activity-3",
        actor: "analysis",
        title: "生成岗位简历 V1",
        detail: "建议调整项目顺序，并修改 3 处经历表述。",
        timeLabel: "6 分钟前",
      },
    ],
    resumeChanges: [
      {
        id: "resume-1",
        section: "智能客服项目",
        before: "负责智能客服产品的需求分析和功能迭代。",
        after: "主导智能客服工作台从需求验证到上线迭代，联合算法与运营建立准确率、转人工率和解决率评估体系。",
        reason: "把“负责功能”改成可追溯的完整产品闭环，并覆盖 JD 的协作与评测要求。",
        evidenceId: "req-1",
        status: "pending",
      },
      {
        id: "resume-2",
        section: "经历顺序",
        before: "增长活动项目位于第一位。",
        after: "将智能客服项目提前到第一位。",
        reason: "AI 产品闭环是该岗位最重要的筛选证据。",
        evidenceId: "req-1",
        status: "accepted",
      },
    ],
    interviewFocus: [
      {
        id: "focus-1",
        question: "你们如何判断大模型效果真的变好了？",
        rationale: "JD 明确要求评测能力，而现有经历只体现人工抽检。",
        readiness: "practice",
      },
      {
        id: "focus-2",
        question: "商业化版本中，你具体负责什么，最后带来了多少收入？",
        rationale: "简历里存在参与描述，但结果与职责尚未核实。",
        readiness: "missing",
      },
      {
        id: "focus-3",
        question: "算法和业务目标冲突时，你如何做取舍？",
        rationale: "已有跨团队项目证据，可以整理为强故事。",
        readiness: "ready",
      },
    ],
  },
  {
    id: "demo-meituan-strategy-pm",
    company: "美团",
    role: "策略产品经理",
    location: "北京",
    stage: "applied",
    stageLabel: "已投递",
    priority: "medium",
    sourceLabel: "招聘官网",
    capturedAtLabel: "8 月 11 日",
    nextEventLabel: "等待 HR 回复 · 2 天",
    recommendation: "apply",
    recommendationLabel: "优先投递",
    recommendationReason: "策略分析、实验设计和业务协作经历覆盖主要要求。",
    evidenceCoverage: { strong: 5, weak: 1, missing: 0, unverified: 0 },
    requirements: [],
    actions: [
      {
        id: "action-m-1",
        title: "准备策略实验失败案例",
        reason: "如果进入面试，这是当前故事库里唯一缺失的类型。",
        dueLabel: "本周",
        priority: "normal",
        status: "todo",
      },
    ],
    activities: [],
    resumeChanges: [],
    interviewFocus: [],
  },
  {
    id: "demo-tencent-ops",
    company: "腾讯",
    role: "产品运营",
    location: "深圳",
    stage: "interviewing",
    stageLabel: "一面待进行",
    priority: "high",
    sourceLabel: "内推链接",
    capturedAtLabel: "8 月 8 日",
    nextEventLabel: "明天 14:00 一面",
    recommendation: "apply",
    recommendationLabel: "正在推进",
    recommendationReason: "已经进入面试，当前重点是把增长案例准备到可追问深度。",
    evidenceCoverage: { strong: 4, weak: 1, missing: 1, unverified: 0 },
    requirements: [],
    actions: [
      {
        id: "action-t-1",
        title: "完成一轮增长案例压力面试",
        reason: "面试将在 24 小时内开始，当前还没有练习反事实追问。",
        dueLabel: "今晚 21:00 前",
        priority: "urgent",
        status: "todo",
      },
    ],
    activities: [],
    resumeChanges: [],
    interviewFocus: [],
  },
];
